from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import datetime
import uuid

class UserMessage(BaseModel):
    """Represents a message sent by the user."""
    user_id: str
    text: str
    timestamp: datetime = Field(default_factory=datetime.now)

class IntentClassification(BaseModel):
    """Represents the classified intent of a user message."""
    intent: str
    confidence: float
    scores: Dict[str, float]

class KnowledgeContext(BaseModel):
    """Represents the knowledge retrieved to answer a query."""
    intent: str
    query: str
    project_data: Optional[Dict[str, Any]] = None
    technical_docs: Optional[List[str]] = None
    decision_history: Optional[List[str]] = None
    agent_info: Optional[Dict[str, Any]] = None

    def to_dict(self):
        return self.dict()

class GeneratedResponse(BaseModel):
    """Represents a response generated by the ResponseGenerator."""
    text: str
    confidence: float
    suggestions: List[str]

class ChatResponse(BaseModel):
    """Represents the final response sent back to the user."""
    message_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: str
    text: str
    intent: str
    confidence: float
    timestamp: datetime = Field(default_factory=datetime.now)
    suggestions: List[str] = []

class ConversationContext(BaseModel):
    """Represents the context of a conversation for a user."""
    user_id: str
    history: List[Dict[str, Any]] = []
    last_interaction: Optional[datetime] = None
