import os
import logging
import ast
from services.qa_agent.app.core.exceptions import TestGenerationError, ArtifactError

logger = logging.getLogger(__name__)

WORKSPACE_DIR = "workspace"

def generate_pytest_file(project_name: str, source_code_path: str) -> str:
    """
    Generates a basic pytest file for a given source code file by parsing it
    to find FastAPI endpoints and creating simple placeholder tests.
    """
    logger.info("Starting test generation for source file.", extra={"props": {"source": source_code_path}})

    try:
        if not os.path.exists(source_code_path):
            raise ArtifactError(f"Source code file not found at path: {source_code_path}", path=source_code_path)

        with open(source_code_path, 'r') as f:
            source_code = f.read()

        tree = ast.parse(source_code)

        api_endpoints = []
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                for decorator in node.decorator_list:
                    # A simple check for decorators like @app.get, @app.post, etc.
                    if isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Attribute):
                        if isinstance(decorator.func.value, ast.Name) and decorator.func.value.id == 'app':
                            if decorator.args and isinstance(decorator.args[0], ast.Constant):
                                api_endpoints.append(decorator.args[0].value)

        project_dir_name = project_name.replace(" ", "_").lower()
        test_dir_path = os.path.join(WORKSPACE_DIR, project_dir_name, "tests")
        os.makedirs(test_dir_path, exist_ok=True)

        source_filename = os.path.basename(source_code_path)
        test_filename = f"test_{source_filename}"
        file_path = os.path.join(test_dir_path, test_filename)

        # Generate the content of the test file
        script_content = f'''"""
Auto-generated by the QA Agent.
Tests for `{source_filename}`.
"""
import pytest
from fastapi.testclient import TestClient

# Note: In a real test environment, the app from the source file would be imported.
# This is a simplified generator.
# from {os.path.splitext(source_filename)[0]} import app

# For now, we create a dummy app to make the test file syntactically valid.
from fastapi import FastAPI
app = FastAPI()

client = TestClient(app)

'''
        if not api_endpoints:
            script_content += "# No API endpoints were found in the source file to test.\n"
        else:
            for endpoint in api_endpoints:
                # Sanitize endpoint path to create a valid Python function name
                test_func_name = f"test_endpoint_{endpoint.replace('/', '_').strip('_')}"
                script_content += f'''
def {test_func_name}():
    """
    Tests the `{endpoint}` endpoint.
    This is a placeholder test. A real test would need the actual app object.
    """
    # response = client.get("{endpoint}")
    # assert response.status_code == 200
    assert True, "Placeholder test for endpoint: {endpoint}"

'''
        with open(file_path, "w") as f:
            f.write(script_content)

        logger.info("Successfully generated test file.", extra={"props": {"path": file_path}})
        return file_path

    except ArtifactError:
        # Re-raise the specific custom exception to be caught by the test
        raise
    except (IOError, ast.ASTError) as e:
        logger.error(f"Failed to read or parse source file: {e}", exc_info=True)
        raise TestGenerationError(f"Failed to process source file: {e}")
    except Exception as e:
        logger.error(f"An unexpected error occurred during test generation: {e}", exc_info=True)
        raise TestGenerationError(f"An unexpected error occurred during test generation: {e}")
