import os
import logging
import re
from services.developer_agent.app.core.exceptions import CodeGenerationError

logger = logging.getLogger(__name__)

WORKSPACE_DIR = "workspace"

def generate_fastapi_endpoint(project_name: str, task_description: str) -> str:
    """
    Generates a basic FastAPI endpoint file from a template.

    This is a simple implementation. A more advanced version would use a proper
    templating engine like Jinja2 and have more sophisticated logic for
    extracting parameters from the task description.

    Args:
        project_name: The name of the project, used for the directory.
        task_description: The detailed description of the task.

    Returns:
        The path to the generated file.
    """
    logger.info("Starting code generation for FastAPI endpoint.", extra={"props": {"project": project_name}})

    try:
        # Sanitize project_name to prevent path traversal.
        # Only allow alphanumeric characters, underscores, and hyphens.
        sane_project_name = re.sub(r'[^a-zA-Z0-9_-]', '', project_name)
        if not sane_project_name:
            raise CodeGenerationError(message="Project name is invalid or empty after sanitization.")

        project_path = os.path.join(WORKSPACE_DIR, sane_project_name)

        # Create the project directory if it doesn't exist
        os.makedirs(project_path, exist_ok=True)

        # Simple logic to derive a filename from the task description
        # Example: "Develop REST API endpoints for features: user_auth" -> "user_auth_routes.py"
        feature_part = task_description.split(":")[-1].strip().replace(" ", "_")
        file_name = f"{feature_part}_routes.py" if feature_part else "default_routes.py"
        file_path = os.path.join(project_path, file_name)

        # Basic Python code template for a FastAPI endpoint
        code_template = f'''"""
Auto-generated by the Developer Agent.
"""
from fastapi import FastAPI

app = FastAPI()

@app.get("/{feature_part}")
def read_{feature_part}():
    """Generated endpoint for {feature_part}."""
    return {{"message": "Endpoint for {feature_part} is active"}}

# Add more generated routes here based on task description...
'''
        with open(file_path, "w") as f:
            f.write(code_template)

        logger.info(f"Successfully generated code artifact.", extra={"props": {"path": file_path}})
        return file_path

    except IOError as e:
        logger.error(f"Failed to write code generation file: {e}", exc_info=True)
        raise CodeGenerationError(message=f"File I/O error during code generation: {e}")
    except Exception as e:
        logger.error(f"An unexpected error occurred during code generation: {e}", exc_info=True)
        raise CodeGenerationError(message=f"An unexpected error occurred: {e}")
