apiVersion: v1
kind: Service
metadata:
  name: web-interface-service
  namespace: flux-prod
spec:
  selector:
    app: web-interface
  ports:
    - name: http
      protocol: TCP
      port: 80 # The port the service will be available on
      targetPort: 8000 # The port the container exposes
  # LoadBalancer type exposes the service externally using a cloud provider's load balancer.
  # For local testing (like Minikube), you might use NodePort instead.
  type: LoadBalancer
